# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hop < Formula
  desc "CLI tool for connecting to named hosts via SSH, Docker, or Kubernetes"
  homepage "https://github.com/geoffyoungs/hop"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.2.1/hop_0.2.1_darwin_amd64.tar.gz"
      sha256 "8502ae8e3829b1924836127c9b41ba65f271ab4aadcedd4f1c93934098865efa"

      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/hop.bash" => "hop"
        zsh_completion.install "completions/hop.zsh" => "_hop"
        fish_completion.install "completions/hop.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.2.1/hop_0.2.1_darwin_arm64.tar.gz"
      sha256 "77084fc1f795a7baa3ba703f2155f7dd5721fbc4e7880aeddc0197d30d4657c3"

      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/hop.bash" => "hop"
        zsh_completion.install "completions/hop.zsh" => "_hop"
        fish_completion.install "completions/hop.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.2.1/hop_0.2.1_linux_amd64.tar.gz"
      sha256 "74cac06a2e3aad5402a128c1dac8547548cd37db4abbe4c6bed2584b646b5aff"
      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/hop.bash" => "hop"
        zsh_completion.install "completions/hop.zsh" => "_hop"
        fish_completion.install "completions/hop.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.2.1/hop_0.2.1_linux_arm64.tar.gz"
      sha256 "80e69849f393a64cabc8700d74200405f0b71ebfb39fb7e5712c97925a7fc4fa"
      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/hop.bash" => "hop"
        zsh_completion.install "completions/hop.zsh" => "_hop"
        fish_completion.install "completions/hop.fish"
      end
    end
  end
end
