# This file was generated by GoReleaser. DO NOT EDIT.
cask "hop" do
  name "hop"
  desc "CLI tool for connecting to named hosts via SSH, Docker, or Kubernetes"
  homepage "https://github.com/geoffyoungs/hop"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hop"
  manpage "docs/man/*.1"
  bash_completion "completions/hop.bash"
  zsh_completion "completions/hop.zsh"
  fish_completion "completions/hop.fish"

  on_macos do
    on_intel do
      url "https://github.com/geoffyoungs/hop/releases/download/v#{version}/hop_#{version}_darwin_amd64.tar.gz"
      sha256 "5b1981122fc467c0e6a6092cdb715f54b62177189732091bbd43ab8ae6f128aa"
    end
    on_arm do
      url "https://github.com/geoffyoungs/hop/releases/download/v#{version}/hop_#{version}_darwin_arm64.tar.gz"
      sha256 "beab2eaefc1ff3c9ac33edd0ed0d0117015a2d01dbc32768bf825f7fe236c77c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/geoffyoungs/hop/releases/download/v#{version}/hop_#{version}_linux_amd64.tar.gz"
      sha256 "ad92f99b832e88c244ed10ba268bdb7e7e1d4067d0c8786d5d1cb4f3bb7828cd"
    end
    on_arm do
      url "https://github.com/geoffyoungs/hop/releases/download/v#{version}/hop_#{version}_linux_arm64.tar.gz"
      sha256 "47eddf4cd16ac31e30bbcf5abcfb6bfd12db1d0721e5d2f224e381d514787025"
    end
  end

  # No zap stanza required
end
