# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hop < Formula
  desc "CLI tool for connecting to named hosts via SSH, Docker, or Kubernetes"
  homepage "https://github.com/geoffyoungs/hop"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.3.0/hop_0.3.0_darwin_amd64.tar.gz"
      sha256 "a29e646dfc7a24d14a7197fe402d76fb8dc01fea2254e15de739c51dfc360a5d"

      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/hop.bash" => "hop"
        zsh_completion.install "completions/hop.zsh" => "_hop"
        fish_completion.install "completions/hop.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.3.0/hop_0.3.0_darwin_arm64.tar.gz"
      sha256 "8db38082ba5f840b7c20612fb6b496b1e538ce49949ef56d9fa92bd11c4aa7e2"

      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/hop.bash" => "hop"
        zsh_completion.install "completions/hop.zsh" => "_hop"
        fish_completion.install "completions/hop.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.3.0/hop_0.3.0_linux_amd64.tar.gz"
      sha256 "ddc9531788be88a1a8292c13966f2e328c2aa91dc62dc95e4b5f594207222fc2"
      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/hop.bash" => "hop"
        zsh_completion.install "completions/hop.zsh" => "_hop"
        fish_completion.install "completions/hop.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.3.0/hop_0.3.0_linux_arm64.tar.gz"
      sha256 "651787d40ea5d2530438ff9d25b11ea1c8529de4e85dab1ae079f190dca3d85a"
      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/hop.bash" => "hop"
        zsh_completion.install "completions/hop.zsh" => "_hop"
        fish_completion.install "completions/hop.fish"
      end
    end
  end
end
