# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hop < Formula
  desc "CLI tool for connecting to named hosts via SSH, Docker, or Kubernetes"
  homepage "https://github.com/geoffyoungs/hop"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.2.2/hop_0.2.2_darwin_amd64.tar.gz"
      sha256 "8b019eaea527160746914947a0ad07bf605ad97f2434aa2de8f5e1ab86ef82ea"

      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/hop.bash" => "hop"
        zsh_completion.install "completions/hop.zsh" => "_hop"
        fish_completion.install "completions/hop.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.2.2/hop_0.2.2_darwin_arm64.tar.gz"
      sha256 "5ab43e152984003a62a5ac1f0abb77b7ad3d9c1d7978b27051d9aa6affe5bb8a"

      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/hop.bash" => "hop"
        zsh_completion.install "completions/hop.zsh" => "_hop"
        fish_completion.install "completions/hop.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.2.2/hop_0.2.2_linux_amd64.tar.gz"
      sha256 "3845d720ae3298869ca495cac471e4e07666db4797d8cf9731e663c1f42a7af6"
      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/hop.bash" => "hop"
        zsh_completion.install "completions/hop.zsh" => "_hop"
        fish_completion.install "completions/hop.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.2.2/hop_0.2.2_linux_arm64.tar.gz"
      sha256 "7a64b8291990cf616f4c1d5c32aca15bec3221988c3b5637165f4765cedd724d"
      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/hop.bash" => "hop"
        zsh_completion.install "completions/hop.zsh" => "_hop"
        fish_completion.install "completions/hop.fish"
      end
    end
  end
end
