# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hop < Formula
  desc "CLI tool for connecting to named hosts via SSH, Docker, or Kubernetes"
  homepage "https://github.com/geoffyoungs/hop"
  version "0.1.0-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.1.0-beta/hop_0.1.0-beta_darwin_amd64.tar.gz"
      sha256 "6c04017889405456cb7de3aa6ed3a3e8b61b40343ec8021bdcda4f6f590db4a9"

      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.1.0-beta/hop_0.1.0-beta_darwin_arm64.tar.gz"
      sha256 "09f3ef0c8eec3a416e6cc37a0e96a6d9df51f6208f1851acc4c2aba38be871dc"

      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.1.0-beta/hop_0.1.0-beta_linux_amd64.tar.gz"
      sha256 "0f1618d289b014761135224f7ed6b56c8dbec2959e011a5d514361c03c29858c"
      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffyoungs/hop/releases/download/v0.1.0-beta/hop_0.1.0-beta_linux_arm64.tar.gz"
      sha256 "a631ecb697896e31d6d585711c49b0f803933ad5b891f76c4438a288cee89019"
      def install
        bin.install "hop"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end
end
